# Generated by Django 2.2.4 on 2019-12-10 00:32

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noteinfo',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
