# Generated by Django 2.2.4 on 2019-12-15 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_taginfo_img_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='noteinfo',
            name='pub_date',
        ),
        migrations.RemoveField(
            model_name='noteinfo',
            name='read_num',
        ),
        migrations.AlterField(
            model_name='taginfo',
            name='img_url',
            field=models.CharField(default='/static/images/html.jpg', max_length=40),
        ),
    ]
